---

- name: Setup database server
  hosts: db
  become: yes
  roles:
    - db

- name: Setup app-for-devops
  hosts: server
  become: yes
  roles:
    - server
  handlers:
    - name: restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted