---

- name: Setup database server
  hosts: db
  become: yes
  roles:
    - db
  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.systemd:
        name: postgresql
        state: restarted

- name: Setup app-for-devops
  hosts: server
  become: yes
  roles:
    - server
  handlers:
    - name: Restart Apache2
      ansible.builtin.service:
        name: apache2
        state: restarted