- name: Generate for database
  ansible.builtin.set_fact:
    login_user: root
    login_pass: lookup('community general.random_string')
    root_pass: lookup('community general.random_string')
  when: lookup('ansible.builtin.env', 'CI') == 'true'

- name: Install PostgreSQL server
  ansible.builtin.apt:
    name:
      - postgresql
      - python3-psycopg2

- name: Create the cluster
  ansible.builtin.command:
    cmd: postgresql-setup --initdb
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Start and enable the service
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Create database user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    role_attr_flags: LOGIN
    state: present
  become: yes
  become_user: postgres

- name: Create database
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    state: present
  become: yes
  become_user: postgres
