- name: Generate for database
  ansible.builtin.set_fact:
    login_user: root
    login_pass: lookup('community general.random_string')
    root_pass: lookup('community general.random_string')
  when: lookup('ansible.builtin.env', 'CI') == 'true'

- name: Install PostgreSQL server
  ansible.builtin.apt:
    name:
      - postgresql
      - python3-psycopg2

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Initialize PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql

- name: Create database user
  ansible.builtin.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    role_attr_flags: LOGIN
    state: present
  become: yes
  become_user: postgres

- name: Create database
  ansible.builtin.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    state: present
  become: yes
  become_user: postgres
