- name: Install PostgreSQL server
  ansible.builtin.apt:
    name:
      - postgresql
      - python3-psycopg2
    state: present
    update_cache: true

- name: Start and enable the service
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Create database
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    encoding: "UTF8"
    state: present
  become: true
  become_user: postgres

- name: Create database user
  community.postgresql.postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    state: present
  become: true
  become_user: postgres
