- name: Generate for database
  ansible.builtin.set_fact:
    login_user: root
    login_pass: lookup('community general.random_string')
    root_pass: lookup('community general.random_string')
  when: lookup('ansible.builtin.env', 'CI') == 'true'

- name: Install PostgreSQL server
  ansible.builtin.apt:
    name:
      - postgresql
      - python3-psycopg2
    state: present
    update_cache: true

- name: Start and enable the service
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Allow PostgreSQL port in UFW
  ansible.builtin.ufw:
    rule: allow
    name: 'PostgreSQL'
    port: '5432'
    proto: 'tcp'

- name: Create database
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    state: present
  become: true
  become_user: postgres

- name: Create database user
  community.postgresql.postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    state: present
  become: true
  become_user: postgres

- name: Configure PostgreSQL to listen on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: '^#?listen_addresses ='
    line: "listen_addresses = '*'"
  notify: Restart PostgreSQL

- name: Allow connections from the application
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    line: "host    all             all             {{ db_host }}/32            md5"
    state: present
  notify: Restart PostgreSQL

- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
  when: ansible.builtin.changed